# Generated by Django 5.2 on 2025-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysmodel',
            name='Image',
            field=models.ImageField(upload_to='media/Category_photos'),
        ),
    ]
