# Generated by Django 5.2 on 2025-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0003_alter_categorysmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysmodel',
            name='Image',
            field=models.ImageField(upload_to='media/Category_photos'),
        ),
    ]
