# Generated by Django 5.2 on 2025-05-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0004_alter_categorysmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('First_Image', models.ImageField(upload_to='media/Products')),
                ('Second_Image', models.ImageField(upload_to='media/Products')),
                ('Material', models.CharField(max_length=30)),
                ('Length', models.CharField(max_length=10)),
                ('Waight', models.CharField(max_length=10)),
                ('Type_Of_work', models.CharField(max_length=20)),
                ('Availability', models.CharField(choices=[('1', 'Available'), ('2', 'Unavailable')], max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RJ.categorysmodel')),
            ],
        ),
    ]
