# Generated by Django 5.2 on 2025-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0005_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='Second_Image',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
