# Generated by Django 5.2 on 2025-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0006_alter_productmodel_second_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='Second_Image',
            field=models.ImageField(upload_to='media/Products'),
        ),
    ]
