# Generated by Django 5.2 on 2025-05-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0007_alter_productmodel_second_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='First_Image',
            field=models.ImageField(upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Second_Image',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
