# Generated by Django 5.2 on 2025-05-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0008_alter_productmodel_first_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysmodel',
            name='Image',
            field=models.ImageField(upload_to='Category_photos'),
        ),
    ]
