# Generated by Django 5.2 on 2025-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0009_alter_categorysmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=20),
        ),
    ]
