# Generated by Django 5.2 on 2025-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0010_registerdatamodel_alter_productmodel_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysmodel',
            name='Name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
