# Generated by Django 5.2 on 2025-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJ', '0013_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
        ),
    ]
